<a href="https://colab.research.google.com/github/Raphaeal19/PyTorch_Learning/blob/master/01_pytorch_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch

# **Tensors**

In [2]:
t1 = torch.tensor(4.)
t1

tensor(4.)

In [3]:
t1.dtype

torch.float32

In [4]:
t2 = torch.tensor([1., 2, 3, 4])
t2

tensor([1., 2., 3., 4.])

In [5]:
t3 = torch.tensor([[5., 6], [7, 8], [9, 10.]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [6]:
t4 = torch.tensor([[
                    [11, 12, 13], 
                    [14, 151, 16]
                  ],
                   [
                    [12, 2453, 1231], 
                    [123, 2345, 234]
                   ]])
t4 

tensor([[[  11,   12,   13],
         [  14,  151,   16]],

        [[  12, 2453, 1231],
         [ 123, 2345,  234]]])

In [7]:
print('t1.shape', t1.shape)
print('t2.shape', t2.shape)
print('t3.shape', t3.shape)
print('t4.shape', t4.shape)

t1.shape torch.Size([])
t2.shape torch.Size([4])
t3.shape torch.Size([3, 2])
t4.shape torch.Size([2, 2, 3])


# **Tensor operations and Gradients**

In [0]:
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)

In [9]:
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [0]:
y.backward()

In [11]:
print('dy/dx: ', x.grad)
print('dy/dw: ', w.grad)
print('dy/db: ', b.grad)

dy/dx:  None
dy/dw:  tensor(3.)
dy/db:  tensor(1.)


# **Numpy interoperability**

In [13]:
import numpy as np

x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [14]:
y = torch.from_numpy(x)
y

tensor([[1, 2],
        [3, 4]])

In [15]:
x.dtype, y.dtype

(dtype('int64'), torch.int64)

In [16]:
z = y.numpy()
z

array([[1, 2],
       [3, 4]])