<a href="https://colab.research.google.com/github/Raphaeal19/PyTorch_Learning/blob/master/02_linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Model to predict crop yields for apples and oranges**

In [0]:
import torch
import numpy as np

In [0]:
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64],
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [0]:
targets = np.array([[56, 70], 
                    [81, 101],
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [4]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [5]:
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[-0.6590,  0.6366, -0.2849],
        [ 0.8423,  0.2977,  0.8546]], requires_grad=True)
tensor([-1.8786, -0.7785], requires_grad=True)


In [0]:
def model(x):
  return x @ w.t()+ b

In [7]:
preds = model(inputs)
print(preds)

tensor([[-19.5889, 117.3986],
        [-24.0663, 156.7565],
        [  9.5616, 161.9522],
        [-52.2697, 129.5543],
        [ -6.1840, 145.7344]], grad_fn=<AddBackward0>)


In [8]:
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


# **Loss Functions**
## **MSE**

In [9]:
diff = preds - targets
diff_sqr = diff * diff
torch.sum(diff_sqr) / diff.numel()

tensor(6164.1167, grad_fn=<DivBackward0>)

In [0]:
def mse(t1, t2):
  diff = t1 - t2
  return torch.sum(diff * diff) / diff.numel()

In [11]:
loss = mse(preds, targets)
print(loss)

tensor(6164.1167, grad_fn=<DivBackward0>)


## **Compute Gradients**

In [0]:
loss.backward()

In [13]:
print(w)
print(w.grad)

tensor([[-0.6590,  0.6366, -0.2849],
        [ 0.8423,  0.2977,  0.8546]], requires_grad=True)
tensor([[-7941.8735, -8530.0605, -5342.5703],
        [ 4467.5977,  3701.6416,  2516.3403]])


In [14]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


# **Adjust weights and biases using gradient descent**

In [15]:
preds = model(inputs)
print(preds)

tensor([[-19.5889, 117.3986],
        [-24.0663, 156.7565],
        [  9.5616, 161.9522],
        [-52.2697, 129.5543],
        [ -6.1840, 145.7344]], grad_fn=<AddBackward0>)


In [16]:
error = mse(preds, targets)
print(error)

tensor(6164.1167, grad_fn=<DivBackward0>)


In [17]:
error.backward()
print(w.grad)
print(b.grad)

tensor([[-7941.8735, -8530.0605, -5342.5703],
        [ 4467.5977,  3701.6416,  2516.3403]])
tensor([-94.7095,  50.2792])


In [0]:
with torch.no_grad():
  w -= w.grad * 1e-5
  b -= b.grad * 1e-5
  w.grad.zero_()
  b.grad.zero_()

In [19]:
print(w)
print(b)

tensor([[-0.5796,  0.7219, -0.2315],
        [ 0.7976,  0.2606,  0.8294]], requires_grad=True)
tensor([-1.8776, -0.7791], requires_grad=True)


In [20]:
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(4302.8110, grad_fn=<DivBackward0>)


## **Train for multiple epochs**

In [0]:
for i in range(100):
  preds = model(inputs)
  loss = mse(preds, targets)
  loss.backward()
  with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [22]:
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(146.9109, grad_fn=<DivBackward0>)


In [23]:
preds


tensor([[ 57.4464,  75.1904],
        [ 77.7154, 103.7780],
        [128.4500, 118.0402],
        [ 24.0663,  66.1297],
        [ 91.9954, 107.3998]], grad_fn=<AddBackward0>)

In [24]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

# **Linear Regression using PyTorch built-ins**

In [0]:
import torch.nn as nn

In [0]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], 
                   [102, 43, 37], [69, 96, 70], [73, 67, 43], 
                   [91, 88, 64], [87, 134, 58], [102, 43, 37], 
                   [69, 96, 70], [73, 67, 43], [91, 88, 64], 
                   [87, 134, 58], [102, 43, 37], [69, 96, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], 
                    [22, 37], [103, 119], [56, 70], 
                    [81, 101], [119, 133], [22, 37], 
                    [103, 119], [56, 70], [81, 101], 
                    [119, 133], [22, 37], [103, 119]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [0]:
from torch.utils.data import TensorDataset

In [0]:
train_ds = TensorDataset(inputs, targets)
# train_ds[[1, 3, 5, 7]]

In [0]:
from torch.utils.data import DataLoader

In [0]:
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [55]:
for xb, yb in train_dl:
  print('batch:')
  print(xb)
  print(yb)
  break

batch:
tensor([[ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [ 69.,  96.,  70.],
        [102.,  43.,  37.],
        [ 73.,  67.,  43.]])
tensor([[ 81., 101.],
        [119., 133.],
        [103., 119.],
        [ 22.,  37.],
        [ 56.,  70.]])


## **nn.Linear**

In [56]:
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.0178, -0.0691, -0.1401],
        [ 0.5720, -0.5688,  0.1627]], requires_grad=True)
Parameter containing:
tensor([0.2184, 0.5548], requires_grad=True)


In [57]:
list(model.parameters())

[Parameter containing:
 tensor([[ 0.0178, -0.0691, -0.1401],
         [ 0.5720, -0.5688,  0.1627]], requires_grad=True),
 Parameter containing:
 tensor([0.2184, 0.5548], requires_grad=True)]

In [58]:
preds = model(inputs)
preds

tensor([[ -9.1359,  11.1970],
        [-13.2086,  12.9646],
        [-15.6156, -16.4641],
        [ -6.1225,  40.4604],
        [-14.9927,  -3.1939],
        [ -9.1359,  11.1970],
        [-13.2086,  12.9646],
        [-15.6156, -16.4641],
        [ -6.1225,  40.4604],
        [-14.9927,  -3.1939],
        [ -9.1359,  11.1970],
        [-13.2086,  12.9646],
        [-15.6156, -16.4641],
        [ -6.1225,  40.4604],
        [-14.9927,  -3.1939]], grad_fn=<AddmmBackward>)

## **Loss Function**

In [0]:
import torch.nn.functional as F

In [0]:
loss_fn = F.mse_loss

In [61]:
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(9444.3330, grad_fn=<MseLossBackward>)


## **Optimizer**

In [0]:
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

## **Train the model**

In [0]:
def fit(num_epochs, model, loss_fn, opt):
  for epoch in range(num_epochs):
    for xb, yb in train_dl:
      pred = model(xb)
      loss = loss_fn(pred, yb)
      loss.backward()
      opt.step()
      opt.zero_grad()
    if(epoch+1) % 10 == 0:
      print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [68]:
fit(100, model, loss_fn, opt)

Epoch [10/100], Loss: 27.1766
Epoch [20/100], Loss: 12.6616
Epoch [30/100], Loss: 17.2396
Epoch [40/100], Loss: 14.1136
Epoch [50/100], Loss: 14.6663
Epoch [60/100], Loss: 10.8448
Epoch [70/100], Loss: 3.8346
Epoch [80/100], Loss: 5.9174
Epoch [90/100], Loss: 7.4679
Epoch [100/100], Loss: 6.8317


In [69]:
preds = model(inputs)
preds

tensor([[ 57.6281,  70.8844],
        [ 80.3618,  99.4026],
        [122.2985, 135.1502],
        [ 23.2213,  39.4719],
        [ 97.4939, 115.5910],
        [ 57.6281,  70.8844],
        [ 80.3618,  99.4026],
        [122.2985, 135.1502],
        [ 23.2213,  39.4719],
        [ 97.4939, 115.5910],
        [ 57.6281,  70.8844],
        [ 80.3618,  99.4026],
        [122.2985, 135.1502],
        [ 23.2213,  39.4719],
        [ 97.4939, 115.5910]], grad_fn=<AddmmBackward>)

In [70]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])