<a href="https://colab.research.google.com/github/Raphaeal19/PyTorch_Learning/blob/master/pytorch_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch

# **Tensors**

In [3]:
t1 = torch.tensor(4.)
t1

tensor(4.)

In [4]:
t1.dtype

torch.float32

In [5]:
t2 = torch.tensor([1., 2, 3, 4])
t2

tensor([1., 2., 3., 4.])

In [6]:
t3 = torch.tensor([[5., 6], [7, 8], [9, 10.]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [10]:
t4 = torch.tensor([[
                    [11, 12, 13], 
                    [14, 151, 16]
                  ],
                   [
                    [12, 2453, 1231], 
                    [123, 2345, 234]
                   ]])
t4 

tensor([[[  11,   12,   13],
         [  14,  151,   16]],

        [[  12, 2453, 1231],
         [ 123, 2345,  234]]])

In [12]:
print('t1.shape', t1.shape)
print('t2.shape', t2.shape)
print('t3.shape', t3.shape)
print('t4.shape', t4.shape)

t1.shape torch.Size([])
t2.shape torch.Size([4])
t3.shape torch.Size([3, 2])
t4.shape torch.Size([2, 2, 3])


# **Tensor operations and Gradients**